

---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1569388/public_html/varotex.id/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp error.html $DEPLOYPATH
    - /bin/cp comingsoon.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R font $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R revolution $DEPLOYPATH
    - /bin/cp -R video $DEPLOYPATH